// OpenHearth AI summaries — turn audit insights into an evidence-cited narrative.
//
// Covers ROADMAP: #1 (monthly AI summary), #2 (hidden-repo explainer),
// #7 (evidence citations), #106 (AI safety card), #115 (transparency).
//
// The stub/template summarizer is deterministic and needs no network, so the
// feature works out of the box. Set OPENHEARTH_LLM=ollama|openai|anthropic to
// upgrade the same evidence into a model-written narrative.

import type { AuditInsights } from "./insights.js";
import { createLLMClient, LLMError, type LLMMessage, type LLMProvider, type LLMProviderId } from "./llm.js";

export type SummaryTone = "neutral" | "hiring" | "humble" | "technical" | "exec";

export interface EvidenceCitation {
  claim: string;
  source: string;
  value: string | number;
}

export interface AISafetyCard {
  provider: LLMProviderId;
  model: string;
  localOnly: boolean;
  whatLeavesMachine: string;
  tokensNeverSent: string;
  transparencyDisclosure: string;
}

export interface AuditSummary {
  text: string;
  provider: LLMProviderId;
  model: string;
  tone: SummaryTone;
  generatedAt: string;
  evidence: EvidenceCitation[];
  safetyCard: AISafetyCard;
}

export interface SummaryOptions {
  tone?: SummaryTone;
  maxTokens?: number;
  signal?: AbortSignal;
}

const TONE_LEADS: Record<SummaryTone, string> = {
  neutral: "Here is what the audit found.",
  hiring: "Here is a portfolio-ready summary of this contributor's impact.",
  humble: "A few notes on the month's contributions, for the record.",
  technical: "Technical breakdown of contribution activity this range.",
  exec: "Executive summary of contribution impact and visibility.",
};

/** Build the list of hard facts every summary must cite (anti-hallucination). */
export function buildEvidence(insights: AuditInsights): EvidenceCitation[] {
  const ev: EvidenceCitation[] = [
    {
      claim: "total contributions in range",
      source: "insights.totalContributions",
      value: insights.totalContributions,
    },
    {
      claim: "unique repositories touched",
      source: "insights.uniqueRepos",
      value: insights.uniqueRepos,
    },
    {
      claim: "pull requests",
      source: "insights.byKind.pr",
      value: insights.byKind.pr,
    },
    {
      claim: "issues",
      source: "insights.byKind.issue",
      value: insights.byKind.issue,
    },
    {
      claim: "reviews",
      source: "insights.byKind.review",
      value: insights.byKind.review,
    },
    {
      claim: "PR merge rate",
      source: "insights.mergeRate",
      value: `${insights.mergeRate}%`,
    },
    {
      claim: "repositories likely hidden by the activity feed",
      source: "insights.reposHiddenByFeed",
      value: insights.reposHiddenByFeed,
    },
  ];
  if (insights.busiestDay) {
    ev.push({ claim: "busiest day", source: "insights.busiestDay", value: insights.busiestDay });
  }
  if (insights.topRepos[0]) {
    ev.push({
      claim: "most active repository",
      source: "insights.topRepos[0]",
      value: `${insights.topRepos[0].repo} (${insights.topRepos[0].count})`,
    });
  }
  return ev;
}

/** Build the AI safety / transparency card for a given provider + model. */
export function buildAISafetyCard(provider: LLMProviderId, model: string): AISafetyCard {
  const localOnly = provider === "stub" || provider === "ollama";
  const whatLeaves =
    provider === "stub"
      ? "Nothing leaves this machine — the summary is generated locally from audit insights."
      : provider === "ollama"
        ? "Audit insights and a prompt are sent to the local Ollama server (default http://localhost:11434)."
        : "Audit insights and a prompt are sent to the configured cloud model provider.";
  return {
    provider,
    model,
    localOnly,
    whatLeavesMachine: whatLeaves,
    tokensNeverSent: "GitHub tokens (PAT/OAuth) are never sent to any model provider.",
    transparencyDisclosure:
      provider === "stub"
        ? "This summary was generated by OpenHearth's built-in template summarizer (no external AI model)."
        : "This summary was generated by an AI model. Verify figures against the cited audit evidence.",
  };
}

function fmtRepoList(repos: Array<{ repo: string; count: number }>, limit: number): string {
  return repos.slice(0, limit).map((r) => `  · ${r.repo} (${r.count})`).join("\n");
}

/** Deterministic, evidence-cited narrative built straight from insights (no LLM). */
export function templateSummary(
  insights: AuditInsights,
  label: string,
  tone: SummaryTone = "neutral"
): string {
  const lines: string[] = [];
  lines.push(`OpenHearth audit · ${label}`);
  lines.push("");
  lines.push(TONE_LEADS[tone]);
  lines.push("");
  lines.push(
    `This range saw ${insights.totalContributions} contributions across ` +
      `${insights.uniqueRepos} unique repositories ` +
      `(insights.totalContributions=${insights.totalContributions}, ` +
      `insights.uniqueRepos=${insights.uniqueRepos}). The work splits into ` +
      `${insights.byKind.pr} pull requests, ${insights.byKind.issue} issues, and ` +
      `${insights.byKind.review} reviews (insights.byKind). The PR merge rate was ` +
      `${insights.mergeRate}% (insights.mergeRate=${insights.mergeRate}).`
  );

  if (insights.reposHiddenByFeed > 0) {
    lines.push("");
    lines.push(
      `GitHub's activity sidebar typically shows ~${insights.reposVisibleOnFeed} busiest ` +
        `repositories before "N repositories not shown". Search API found ` +
        `${insights.uniqueRepos}, so about ${insights.reposHiddenByFeed} lower-activity ` +
        `repositories are likely truncated from the feed ` +
        `(insights.reposHiddenByFeed=${insights.reposHiddenByFeed}). These are the repos ` +
        `that earned contributions but won't appear on the profile sidebar.`
    );
  } else {
    lines.push("");
    lines.push(
      `All ${insights.uniqueRepos} repositories are within the activity feed's visible window ` +
        `for this range (insights.reposHiddenByFeed=0).`
    );
  }

  if (insights.busiestDay) {
    lines.push("");
    lines.push(`The busiest day was ${insights.busiestDay} (insights.busiestDay).`);
  }

  if (insights.topRepos.length > 0) {
    lines.push("");
    lines.push("Top repositories by activity (likely visible on the feed):");
    lines.push(fmtRepoList(insights.topRepos, 8));
  }

  if (insights.likelyHiddenRepos.length > 0) {
    lines.push("");
    lines.push("Likely hidden repositories (least activity first, most likely truncated):");
    lines.push(fmtRepoList(insights.likelyHiddenRepos, 10));
    if (insights.likelyHiddenRepos.length > 10) {
      lines.push(`  … and ${insights.likelyHiddenRepos.length - 10} more.`);
    }
  }

  lines.push("");
  lines.push(
    "Every figure above is cited from the audit insights — no claims are invented. " +
      "(generated by OpenHearth's built-in template summarizer; no external AI model was used.)"
  );
  return lines.join("\n");
}

/** Build the chat messages sent to a real LLM provider (stub bypasses this). */
export function buildSummaryPrompt(
  insights: AuditInsights,
  label: string,
  tone: SummaryTone = "neutral"
): LLMMessage[] {
  const evidence = buildEvidence(insights);
  const facts = evidence.map((e) => `- ${e.claim}: ${e.value} (source: ${e.source})`).join("\n");
  const topRepos = insights.topRepos.slice(0, 10).map((r) => `${r.repo} (${r.count})`).join(", ");
  const hiddenRepos = insights.likelyHiddenRepos
    .slice(0, 15)
    .map((r) => `${r.repo} (${r.count})`)
    .join(", ");
  const system =
    "You are OpenHearth's audit narrator. Write a concise, accurate narrative of a GitHub " +
    "contributor's activity for a given range. Rules:\n" +
    "1. Cite every number from the provided evidence (use the exact values).\n" +
    "2. Never invent repos, counts, or dates that are not in the evidence.\n" +
    "3. If the evidence shows hidden repos, explain why they are likely truncated.\n" +
    "4. Keep it to ~150-250 words, plain prose (no markdown headings).\n" +
    "5. Do not request or mention GitHub tokens.\n";
  const user =
    `Audit label: ${label}\nTone: ${tone}\n\n` +
    `Evidence (cite these exactly):\n${facts}\n\n` +
    `Top repositories: ${topRepos || "(none)"}\n` +
    `Likely hidden repositories (least activity first): ${hiddenRepos || "(none)"}\n\n` +
    `Write the summary now.`;
  return [
    { role: "system", content: system },
    { role: "user", content: user },
  ];
}

/** Generate an audit summary. Defaults to the stub/template provider (no network). */
export async function generateAuditSummary(
  insights: AuditInsights,
  label: string,
  provider?: LLMProvider,
  opts: SummaryOptions = {}
): Promise<AuditSummary> {
  const tone = opts.tone ?? "neutral";
  const client = provider ?? createLLMClient();
  const evidence = buildEvidence(insights);
  const safetyCard = buildAISafetyCard(client.id, client.model);
  let text: string;
  if (client.id === "stub") {
    text = templateSummary(insights, label, tone);
  } else {
    const messages = buildSummaryPrompt(insights, label, tone);
    try {
      text = await client.complete({
        messages,
        maxTokens: opts.maxTokens,
        temperature: 0.2,
        signal: opts.signal,
      });
    } catch (err) {
      if (err instanceof LLMError) throw err;
      throw new LLMError(client.id, err instanceof Error ? err.message : String(err));
    }
  }
  return {
    text,
    provider: client.id,
    model: client.model,
    tone,
    generatedAt: new Date().toISOString(),
    evidence,
    safetyCard,
  };
}

const CAPTION_LEADS: Record<SummaryTone, string> = {
  neutral: "My GitHub activity for",
  hiring: "Portfolio snapshot —",
  humble: "A quiet month of contributions for",
  technical: "Contribution audit for",
  exec: "Impact summary for",
};

const CAPTION_PLATFORMS: Record<SummaryTone, string> = {
  neutral: "share",
  hiring: "LinkedIn",
  humble: "README",
  technical: "team update",
  exec: "exec brief",
};

function evidenceValue(summary: AuditSummary, source: string): string | number | undefined {
  return summary.evidence.find((e) => e.source === source)?.value;
}

/**
 * Build a compact, paste-ready share-card caption (LinkedIn / X / README blurb)
 * from an audit summary + the public share URL. ROADMAP #4.
 */
export function buildShareCaption(summary: AuditSummary, shareUrl: string): ShareCaption {
  const lead = CAPTION_LEADS[summary.tone];
  const total = evidenceValue(summary, "insights.totalContributions") ?? 0;
  const repos = evidenceValue(summary, "insights.uniqueRepos") ?? 0;
  const prs = evidenceValue(summary, "insights.byKind.pr") ?? 0;
  const mergeRate = evidenceValue(summary, "insights.mergeRate") ?? "0%";
  const hidden = evidenceValue(summary, "insights.reposHiddenByFeed") ?? 0;

  const parts: string[] = [
    `${lead} ${total} contributions across ${repos} repositories — ` +
      `${prs} pull requests (${mergeRate} merge rate)`,
  ];
  if (Number(hidden) > 0) {
    parts.push(
      `~${hidden} lower-activity repos are likely hidden from the GitHub activity feed`
    );
  }
  parts.push(`Full report: ${shareUrl}`);

  return {
    text: parts.join(". ") + ".",
    platform: CAPTION_PLATFORMS[summary.tone],
  };
}

export interface ShareCaption {
  text: string;
  /** Suggested sharing platform based on the tone preset. */
  platform: string;
}


